# Generated by Django 2.0.6 on 2019-02-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('t_n1', models.CharField(max_length=200)),
                ('t_n2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mates_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=200)),
                ('node_time', models.DateTimeField(auto_now_add=True)),
                ('mate_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.ClassMates')),
            ],
        ),
    ]
